### ISSUE TITLE
ResetDateTime: /usr/bin/env: 'python\r': No such file or directory

### ISSUE THREAD

**Issue by danjames92** [clinton-hall/GetScripts#20]
With latest testing release NZBGet 21

`Post-process-script ResetDateTime.py for REDACTED.FILE.NAME.2018.LiMiTED.1080p.BluRay.x264-CADAVER failed (terminated with unknown status) INFO`    
`Sun Oct 07 2018 22:27:04    ResetDateTime: /usr/bin/env: 'python\r': No such file or directory`

**Comment by clinton-hall** [comment]
Ok, this is strange `\r` appearing in the shebang.

How did you clone this repo? did you download a zip and extract via Windows? if so you may need to run `dos2unix` on these files. best bet is to clone in linux using git.

Otherwise I can't account for, or replicate, that error on the current branch.

**Comment by danjames92** [comment]
Yeah initially I copied it into a `.txt` then moved it from a `.txt` to `.py`.

This time I git cloned the repo and then moved the script into the correct location and it's working now.

Thanks clinton for these awesome scripts.
